# 1 - 주어진 데이터에 로지스틱 회귀모형 적합 후, Mean Accuracy 찍기


In [64]:
import numpy as np
import pandas as pd

In [65]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [66]:
data = pd.read_csv('sampled_data.csv') 

In [67]:
data.head()

Time        V1        V2        V3        V4        V5        V6  \
0  136330  2.108286 -0.020359 -2.234273 -0.124080  0.559843 -1.315913   
1  116819  2.080143 -0.075408 -1.359381  0.261263  0.232201 -0.797886   
2   27917  1.152650  0.204938  0.441832  1.211595 -0.254895 -0.383380   
3   97443 -0.389692  0.410148  0.616187 -0.686644  1.040312 -0.322199   
4   17920 -1.306986  0.183306  3.164803  0.810135  1.529576  2.388322   

         V7        V8        V9  ...         V21       V22       V23  \
0  0.631887 -0.385490  0.150628  ...    0.162940  0.519705 -0.091751   
1  0.233487 -0.330165  0.493154  ...   -0.317765 -0.784150  0.233078   
2 -0.004286 -0.019590  0.085094  ...    0.066674  0.209828 -0.054351   
3  0.523625 -0.037453  1.319237  ...    0.116692  0.685267 -0.182303   
4  0.551279 -0.054401  1.675481  ...   -0.203993  0.556523  0.146513   

        V24       V25       V26       V27       V28  Amount  Class  
0 -0.379542  0.418822  0.248646 -0.098857 -0.094773    7.70      0  
1 -0.636937 -0.191137  0.234986 -0.070648 -0.062794   17.99      0  
2  0.058103  0.515330 -0.299402  0.032551  0.022865   21.00      0  
3  0.767857 -0.242738  0.009678  0.115370  0.176041    6.60      0  
4 -1.128693 -0.633623 -0.454903 -0.826329 -0.826186    4.95      0  

[5 rows x 31 columns]

In [68]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [69]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, :-1], data.iloc[:, -1], test_size=0.3, random_state=0)

In [70]:
scaler = StandardScaler() # Scaling
scaler.fit_transform(data)

array([[ 0.87599191,  1.10227326, -0.01383661, ..., -0.29889867,
        -0.34162683, -0.04276894],
       [ 0.46599202,  1.08762774, -0.04747727, ..., -0.19381068,
        -0.29798293, -0.04276894],
       [-1.4021752 ,  0.60496356,  0.12384231, ...,  0.08768119,
        -0.28521635, -0.04276894],
       ...,
       [-0.42810237, -1.77186915, -0.42136644, ..., -0.90645255,
         0.37580428, -0.04276894],
       [ 0.90608364,  0.67055034, -1.06901447, ...,  0.00759972,
         1.21623571, -0.04276894],
       [-1.90993121,  0.72058018, -0.22056932, ...,  0.07781589,
        -0.25934387, -0.04276894]])

In [71]:
data_new = pd.DataFrame(scaler.fit_transform(data), columns = ['time','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17','V18','V19','V20','V21','V22','V23','V24','V25','V26','V27','V28','Amount','class'])

In [72]:
data_new

time        V1        V2        V3        V4        V5        V6  \
0      0.875992  1.102273 -0.013837 -1.519427 -0.092494  0.415984 -0.996862   
1      0.465992  1.087628 -0.047477 -0.930583  0.178984  0.173824 -0.604853   
2     -1.402175  0.604964  0.123842  0.281721  0.848501 -0.186188 -0.291182   
3      0.058829 -0.197667  0.249246  0.399070 -0.488826  0.771099 -0.244885   
4     -1.612250 -0.675024  0.110623  2.114412  0.565669  1.132714  1.806258   
5     -0.765311 -0.211634  0.304681  1.218465  0.222991  0.118027  0.393519   
6      0.654528  0.948677 -0.311705 -1.119129  0.101497  0.228270 -0.155660   
7      1.268298 -0.271639  0.788771 -0.155698 -0.444375  0.093140 -0.796843   
8     -0.534222  0.600379  0.033432  0.226896  0.993220 -0.221613 -0.163938   
9     -1.421865  0.659971  0.237587  0.197597  0.479818 -0.241270 -0.805187   
10     1.077703  1.106625 -0.434227 -0.732299 -0.378025 -0.681139 -0.794978   
11    -0.550213 -0.360374  0.754001  1.124566  0.025190 -0.218534 -0.927505   
12     1.117314 -0.057730  0.349293 -0.974840 -0.059983 -0.010329 -0.455877   
13    -1.266699 -0.219496  0.348201  1.237336 -0.145174 -0.166553 -0.149909   
14    -0.785715 -0.685419  1.497640  1.250847  3.159092 -0.254607  1.066600   
15    -0.715151 -1.233445 -0.862012  1.054376 -1.732123 -0.733903 -0.306951   
16     1.047023  1.115640 -0.697576 -0.471299 -0.773448 -0.649184  0.088816   
17     0.320409  1.046050 -0.177868 -0.183440  0.362173 -0.515977 -0.506282   
18    -0.589404  0.558907 -0.240973  0.505790  0.391562 -0.711645 -0.336704   
19    -0.855817  0.760346 -0.092169 -0.029310 -0.429765 -0.493148 -1.183283   
20    -1.373029  0.441926 -0.882183  0.231294 -0.853305 -0.709837  0.611444   
21    -0.876726 -0.243469  0.256559  1.450696 -0.847857  0.108554 -0.142430   
22    -0.427703  0.581215  0.030649  0.476344  0.647406 -0.408206 -0.393787   
23    -1.492030 -0.763288 -1.484371  1.050885 -0.222720 -2.466030  1.565713   
24     0.677412 -5.796051 -1.669571 -1.666763 -0.068709  3.502486  3.227742   
25     0.976249 -0.286652  0.463463  0.027390 -0.430895  0.445897 -0.886392   
26    -0.586651  0.560052  0.315192  0.409927  1.677312  0.057622  0.085034   
27    -0.352053 -0.268997  0.677792  0.930115 -0.169015  0.203059 -0.444858   
28    -1.041474  0.629025  0.176726  0.258197  0.437086 -0.319047 -0.659822   
29    -0.010979 -0.270927  1.146158 -0.608459  0.843371  0.992878 -0.291113   
...         ...       ...       ...       ...       ...       ...       ...   
28450 -0.554227  0.519605 -0.109372  0.043208  0.897711 -0.283041 -0.488660   
28451  0.478558 -0.237555 -0.132723  1.878672 -0.929730 -0.943068  0.292399   
28452  0.770440 -0.429575  0.456266 -0.442233  0.104710  1.928690  3.232859   
28453 -1.815958 -1.102943 -0.515482  1.600965 -0.137978  0.411303  1.444260   
28454 -0.517327  0.698739  0.236444 -1.473205 -0.221273  1.954426  2.123906   
28455  1.196158  1.069983 -0.577413 -1.108225 -0.345662 -0.289827 -0.581079   
28456 -1.538849 -5.005354  3.305127 -4.990266  1.166641 -4.497402 -1.467747   
28457  1.454312 -0.172081  0.559060 -0.084688 -0.547128  0.200310 -0.502873   
28458  0.977867  1.202248 -0.820031 -0.575223 -1.157305 -0.801730 -0.221855   
28459 -0.321331 -0.881745  0.129938  1.299035 -1.637378 -0.411446 -0.909669   
28460 -0.327783 -0.374813  0.485731  1.391371  1.245095 -0.675737  0.459507   
28461 -0.550718 -0.210055  0.558359  0.742169 -0.120984  0.251625 -0.037108   
28462 -1.154213 -0.521673 -2.596759 -0.349136  1.098708 -1.784707 -0.053812   
28463 -1.038658  0.674651 -0.484064  0.549492 -0.613534 -0.810290  0.198305   
28464  1.230389  0.046056  0.404335  0.260349  0.534284  0.079445  0.095121   
28465  0.533110 -0.445593  0.636229 -0.744515  0.736394  1.019522 -1.202643   
28466 -0.665810 -0.791326  1.370136  0.071199  0.631717 -0.511314 -0.687730   
28467  0.663290 -0.105094 -0.417458  0.194763 -1.313148  0.716263  0.991651   
28468  0.951999 -1.659913  0.554983 -1.845336 -2.792797 -0.12

In [73]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((19936, 30), (8544, 30), (19936,), (8544,))

In [74]:
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [75]:
y_pred = classifier.predict(X_test) # class 예측


In [76]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [86]:
X_test_proba=classifier.predict_proba(X_test)

In [87]:
classifier.score(X_test, y_test) # return mean accuracy

0.9992977528089888

# 2- Confusion Matrix 찍어보기 → Mean Accuracy와 비교

In [79]:
from sklearn.metrics import *

In [80]:
f1_score(y_pred, y_test) # f1 score

#f1_score가 더 작은 확률을 가지고 있다.

0.7272727272727272

In [81]:
confusion_matrix(y_pred, y_test)

array([[8530,    4],
       [   2,    8]], dtype=int64)

# 3- curoff 조정하기

In [89]:
for thres in [0.5, 0.4, 0.3, 0.2, 0.1, 0.01]:
    print('cut-off: ', thres)
    print(confusion_matrix(y_test, X_test_proba[:,1]>thres))
    print('auc : ', roc_auc_score(y_test, X_test_proba[:,1]>thres))
    print('recall', recall_score(y_test, X_test_proba[:,1]>thres))
    print('-'*35)
    
#thres에 값을 넣어서 curoff를 조정했다.

cut-off:  0.5
[[8530    2]
 [   4    8]]
auc :  0.8332161275199249
recall 0.6666666666666666
-----------------------------------
cut-off:  0.4
[[8530    2]
 [   3    9]]
auc :  0.8748827941865917
recall 0.75
-----------------------------------
cut-off:  0.3
[[8530    2]
 [   3    9]]
auc :  0.8748827941865917
recall 0.75
-----------------------------------
cut-off:  0.2
[[8529    3]
 [   3    9]]
auc :  0.8748241912798875
recall 0.75
-----------------------------------
cut-off:  0.1
[[8519   13]
 [   3    9]]
auc :  0.8742381622128458
recall 0.75
-----------------------------------
cut-off:  0.01
[[8211  321]
 [   1   11]]
auc :  0.939521800281294
recall 0.9166666666666666
-----------------------------------
