# Assignment2: Logistic Regression 구현
1) 제가 제시한 틀을 사용하여 구현을 할 필요는 없습니다. 원하시는 대로 구현하시면 됩니다.  
2) 단, code copy는 허용하지 않습니다. 코드 주석을 꼭 상세히 달아주세요. 주석이 부족한 경우, 미제출로 간주합니다.

In [4]:
import math, random
from functools import partial,reduce
from linear_algebra import *
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
"""
data 설명
1) Label: 유료 계정 등록 여부(target)
2) bias: 회귀 모형에서의 상수항을 위한 term (추정 시 포함하지 않아도 ok)
3) experience: 근속연수
4) salary: 연봉

어떤 사용자가 유료 계정을 등록할지(Label == 1)에 대한 예측을 로지스틱 회귀 모형으로 진행합니다.
"""

'\ndata 설명\n1) Label: 유료 계정 등록 여부(target)\n2) bias: 회귀 모형에서의 상수항을 위한 term (추정 시 포함하지 않아도 ok)\n3) experience: 근속연수\n4) salary: 연봉\n\n어떤 사용자가 유료 계정을 등록할지(Label == 1)에 대한 예측을 로지스틱 회귀 모형으로 진행합니다.\n'

In [17]:
data = pd.read_csv('assignment_2.csv') #파일 불러오기

In [7]:
data #파일 확인

Label  bias  experience  salary
0        1     1         0.7   48000
1        0     1         1.9   48000
2        1     1         2.5   60000
3        0     1         4.2   63000
4        0     1         6.0   76000
5        0     1         6.5   69000
6        0     1         7.5   76000
7        0     1         8.1   88000
8        1     1         8.7   83000
9        1     1        10.0   83000
10       0     1         0.8   43000
11       0     1         1.8   60000
12       1     1        10.0   79000
13       0     1         6.1   76000
14       0     1         1.4   50000
15       0     1         9.1   92000
16       0     1         5.8   75000
17       0     1         5.2   69000
18       0     1         1.0   56000
19       0     1         6.0   67000
20       0     1         4.9   74000
21       1     1         6.4   63000
22       0     1         6.2   82000
23       0     1         3.3   58000
24       1     1         9.3   90000
25       1     1         5.5   57000
26       0     1         9.1  102000
27       0     1         2.4   54000
28       1     1         8.2   65000
29       0     1         5.3   82000
..     ...   ...         ...     ...
170      0     1         6.2   70000
171      1     1         6.6   56000
172      0     1         6.3   76000
173      0     1         6.5   78000
174      0     1         5.1   59000
175      1     1         9.5   74000
176      0     1         4.5   64000
177      0     1         2.0   54000
178      0     1         1.0   52000
179      0     1         4.0   69000
180      0     1         6.5   76000
181      0     1         3.0   60000
182      0     1         4.5   63000
183      0     1         7.8   70000
184      1     1         3.9   60000
185      0     1         0.8   51000
186      0     1         4.2   78000
187      0     1         1.1   54000
188      0     1         6.2   60000
189      0     1         2.9   59000
190      0     1         2.1   52000
191      0     1         8.2   87000
192      0     1         4.8   73000
193      1     1         2.2   42000
194      0     1         9.1   98000
195      0     1         6.5   84000
196      0     1         6.9   73000
197      0     1         5.1   72000
198      1     1         9.1   69000
199      1     1         9.8   79000

[200 rows x 4 columns]

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# 모듈 불러오기

In [9]:
X_train, X_test, y_train, y_test = train_test_split( data , data["Label"],  random_state=0)

# train 데이터와 test 데이터로 split

In [10]:
scaler = StandardScaler() # Scaling
scaler.fit_transform(data)

array([[ 1.68705478,  0.        , -1.51324933, -1.20660229],
       [-0.59274898,  0.        , -1.09075068, -1.20660229],
       [ 1.68705478,  0.        , -0.87950136, -0.43231205],
       [-0.59274898,  0.        , -0.2809616 , -0.23873949],
       [-0.59274898,  0.        ,  0.35278637,  0.60007494],
       [-0.59274898,  0.        ,  0.52882748,  0.14840563],
       [-0.59274898,  0.        ,  0.88090968,  0.60007494],
       [-0.59274898,  0.        ,  1.09215901,  1.37436518],
       [ 1.68705478,  0.        ,  1.30340833,  1.05174424],
       [ 1.68705478,  0.        ,  1.7611152 ,  1.05174424],
       [-0.59274898,  0.        , -1.47804111, -1.52922322],
       [-0.59274898,  0.        , -1.1259589 , -0.43231205],
       [ 1.68705478,  0.        ,  1.7611152 ,  0.7936475 ],
       [-0.59274898,  0.        ,  0.38799459,  0.60007494],
       [-0.59274898,  0.        , -1.26679178, -1.07755392],
       [-0.59274898,  0.        ,  1.44424122,  1.63246192],
       [-0.59274898,  0.

In [11]:
data = pd.DataFrame(scaler.fit_transform(data), columns = ['Label','bias','experience','salary'])
# 스케일러로 데이터 스케일링 해주기

In [13]:
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

#train 시키기

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [14]:
y_pred = classifier.predict(X_test) # class 예측
y_pred

#x_test 값으로 y값 예측

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

In [15]:
classifier.predict_proba(X_test)

array([[0.86959313, 0.13040687],
       [0.71776463, 0.28223537],
       [0.85339506, 0.14660494],
       [0.77191444, 0.22808556],
       [0.82157418, 0.17842582],
       [0.76006608, 0.23993392],
       [0.69137171, 0.30862829],
       [0.53080424, 0.46919576],
       [0.51226581, 0.48773419],
       [0.63649998, 0.36350002],
       [0.55362956, 0.44637044],
       [0.67077925, 0.32922075],
       [0.746954  , 0.253046  ],
       [0.75599945, 0.24400055],
       [0.78769691, 0.21230309],
       [0.74819446, 0.25180554],
       [0.83758374, 0.16241626],
       [0.8175064 , 0.1824936 ],
       [0.79602146, 0.20397854],
       [0.72157453, 0.27842547],
       [0.61467715, 0.38532285],
       [0.83013536, 0.16986464],
       [0.66540371, 0.33459629],
       [0.79293795, 0.20706205],
       [0.6795117 , 0.3204883 ],
       [0.59969529, 0.40030471],
       [0.82277551, 0.17722449],
       [0.85303402, 0.14696598],
       [0.71917595, 0.28082405],
       [0.74140038, 0.25859962],
       [0.

In [16]:
classifier.score(X_test, y_test) # 정확도 

0.8

### 0. Gradient Descent

In [ ]:
def step(v, direction, step_size):
    return [v_i + step_size * direction_i
           for v_i, direction_i in zip(v, direction)]

v = [random.randint(-10,10) for i in range(3)]
    """
    한 지점에서 step size만큼 이동하는 step 함수를 구현하세요.
    필요한 인자는 3가지입니다.
    """

In [ ]:
def safe(f):
    """
    f에 대한 예외처리를 위한 함수(f가 infinite일 때)
    """
    def safe_f(*args, **kargs):
        try:
            return f(*args, **kwargs)
        except:
            return float('inf')
    return safe_f

In [ ]:
def minimize_bgd(target_fn, gradient_fn, theta_0, tolerance = 0.00001): # bgd: batch gradient descent
   
    step_sizes = [100, 10, 1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
    
    # 시작점 설정
    theta = theta_0
    target_fn = safe(target_fn) # 오류를 처리할 수 있는 target_fn으로 변환
    value = target_fn(theta) # 최소화시키려는 값
    
    while True:
        gradient = gradient_fn(theta) # gradient값 계산
        next_thetas = [step(theta, gradient, -step_size) for step_size in step_sizes] #### update thetas --> 각 step sizes에 따른 theta값을 list형태로 리턴
        
        # 함수를 최소화시키는 theta 선택
        obj = next_thetas ## 알맞은 obj, key 값을 채워넣으세요.
        key = target_fn
        next_theta = min(obj, key = key)
        
        # tolerance만큼 수렴하면 멈춤
        temp = abs(value - target_fn(next_theta))
        if temp < tolerance:
            return theta
        else: 
            theta, value = next_theta, target_fn(theta)
        

In [ ]:
def stochastic():
    """
    sgd 구현 (추가적인 부분이니 필수는 아닙니다.)
    """

### 1. 로지스틱 함수
해당 함수는 1/(1+exp[-(ax+b)]로 표현되었음을 기억합시다.

In [ ]:
def logistic(x):
     return 1 / (1 + np.exp(-x))

In [ ]:
# 추가문제: softmax 구현

def softmax(a) :
    exp_a = np.exp(a) #a에 exp 함수를 하여 exp_a 만들기
    sum_exp_a = np.sum(exp_a) #exp_a의 합
    y = exp_a / sum_exp_a #exp_a에서 sum_exp_a 나누기
    
    return y

a = np.array([0.3, 2.9, 4.0]) #a 배열 임의로 정의

### 2. 목적함수 구현
최적화할 목적함수를 구현합니다.

In [ ]:
def logistic_log_likelihood_i(x_i, y_i, beta): # 개별 데이터포인트에 대한 likelihood 값

    cond = (y_i == 1) #y_i이 1인지에 대한 변수
    if cond:
        return math.log(logistic(dot(x_i, beta))) # 최적화하여 y_i가 1이라면 1에서 x_i과 beta값을 곱하여 logistic화 시킨다.
    else:
        return math.log(1-logistic(dot(x_i,beta)))  # y_i가 1이 아닐경우 , 1에서 x_i과 beta값을 곱하여 logistic화 시킨다음 1에서 뺀다.

    
    


In [ ]:
def logistic_log_likelihood(x, y, beta): # 전체 데이터에 대한 likelihood

    return sum(logistic_log_likelihood_i(x_i, y_i, beta)
              for x_i, y_i in zip(x,y))

#b는 모두 차원을 가진 벡터, x도 역시 벡터이다.

### 3. Gradient for Log Reg
아래 3가지 함수에 대해 해당 함수의 인자와 기능을 자세히 설명하세요.

In [ ]:
def logistic_log_partial_ij(x_i, y_i, beta, j):
    """
    특정 데이터 x_i에 대한 beta_j의 gradient 값 --> 상수 형태의 리턴값
    """
    return (y_i - logistic(dot(x_i, beta))) * x_i[j] # j: beta의 index

def logistic_log_gradient_i(x_i, y_i, beta):
    """
    x_i(row)에 대한 beta의 gradient 값(column 개수만큼) --> 리스트 형태의 리턴값을 가짐
    """
    return [logistic_log_partial_ij(x_i, y_i, beta, j) for j, _ in enumerate(beta)]

def logistic_log_gradient(x, y, beta):
    """
    전체 데이터에 대한 beta의 gradient 값 
    --> 이중 리스트를 vector_add 시켜서 beta_j에 대한 gradient값들을 rowSum 해놓은 리스트를 리턴
    """
    return reduce(vector_add, [logistic_log_gradient_i(x_i, y_i, beta) for x_i, y_i in zip(x,y)])
# reduce ~ == np.sum(iter, axis = 0)

###설명###

### 4. Model Fitting
위에서 구현한 목적함수와 Gradient Descent Algorithm을 이용하여 Model을 Fitting 시켜보세요.  

In [ ]:
X = data.drop('Label', axis = 1)
y = data['Label']

In [ ]:
X=X.as_matrix() # matrix로 변환해주어야 합니다!
y=y.as_matrix()

In [ ]:
X[:10] ## X: 데이터 스케일이 필요함.

In [ ]:
from sklearn.preprocessing import StandardScaler


In [ ]:
ss = StandardScaler()
X_scaled = ss.fit_transform(data.drop(['Label'], axis = 1)) # X_scaled


In [ ]:
for i,_ in enumerate(X_scaled):
    X_scaled[i][0] = 1 # bias term 추가

In [ ]:
random.seed(0)
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
# 아래에 Model Fitting 진행
# partial을 이용해 fn과 gradient_fn 구현

fn = partial(logistic_log_likelihood, x_train, y_train)
gradient_fn = partial(logistic_log_gradient, x_train, y_train)

beta_0 = [random.random() for _ in range(3)] # 임의의 시작점
#beta_0 = [1,1,1]

# 경사 하강법으로 최적화
beta_hat = minimize_bgd(neg(fn), neg_all(gradient_fn), beta_0)
beta_hat