In [79]:
import numpy as np
from numpy.linalg import inv 

def estimate_beta(x,y):
    x2 = np.transpose(x) # x' 구하기
    x3 = np.dot(x,x2)  #x'x 구하기
    x2y = np.dot(x2,y) #x'y 구하기
    
    x4 = np.linalg.inv(x3) #역행렬 구하기 위해서 inverse 사용 (X'X)-1
    beta_hat = np.dot(x4,x2y) #베타헷 = (X'X)-1X'Y
    
    return beta_hat

In [80]:
#x행렬에 intercept를 추가해야함
x = np.array([ [1, 0, 1],
               [1, 2, 3],
               [1, 3, 8]]) #3x3
y = np.transpose(np.array([1, 3, 7])) #3x1

In [81]:
estimate_beta(x,y)

array([ 3.65625, -1.46875,  1.0625 ])

In [82]:
x

array([[1, 0, 1],
       [1, 2, 3],
       [1, 3, 8]])

In [83]:
y

array([1, 3, 7])

In [84]:
estimate_beta(x,y)

array([ 3.65625, -1.46875,  1.0625 ])

In [85]:
#sklearn은 디폴트로 intercept가 fit되므로, 데이터에 intercept가 포함된 경우는 fit_intercept=False로 해야함

In [86]:
from sklearn.linear_model import LinearRegression

In [87]:
reg = LinearRegression(fit_intercept=False).fit(x, y)

In [88]:
reg.coef_

array([0.25, 0.25, 0.75])